apiVersion: v1
kind: Pod
metadata:
  name: busybox-sleep3
spec:
  containers:
    - name: busybox3
      image: busybox
      args:
        - sleep
        - infinity
      resources:
        limits:
          hardware-vendor.example/foo: 1
